version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-tododb}
      MYSQL_USER: ${DB_USER:-todo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-todo}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: todo-app:latest
    container_name: todo-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-tododb}
      DB_USER: ${DB_USER:-todo}
      DB_PASSWORD: ${DB_PASSWORD:-todo}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  db_data:


